version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment:
            RFSIMULATOR: server
            USE_SA_TDD_MONO: 'yes'
            GNB_NAME: gnb-rfsim
            TAC: 1
            MCC: '208'
            MNC: '99'
            MNC_LENGTH: 2
            NSSAI_SST: 1
            AMF_IP_ADDRESS: 192.168.71.132
            GNB_NGA_IF_NAME: eth0
            GNB_NGA_IP_ADDRESS: 192.168.71.140
            GNB_NGU_IF_NAME: eth0
            GNB_NGU_IP_ADDRESS: 192.168.71.140
            SDR_ADDRS: serial=XXXXXXX
            USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --gNBs.[0].um_on_default_drb 1 --MACRLCs.[0].dl_harq_round_max 1 --MACRLCS.[0].ul_harq_round_max 1 --rfsimulator.wait_timeout 20  --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.71.140
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        driver: overlay
        name: rfsim5g-oai-public-net
        external: true
        
    traffic_net:
        driver: overlay
        name: rfsim5g-oai-traffic-net
        external: true